library(bayesplot)
# library(biscale)
library(colorspace)
library(dplyr)
library(extrafont)
library(farver)
library(ggplot2)
library(ggtext)
library(glue)
library(magrittr)
library(methods)
# library(paletteer)
library(pals)
library(patchwork)
library(purrr)
library(ragg)
# library(rcartocolor)
# library(RColorBrewer)
library(rlang)
library(scales)
library(scico)
library(stringr)
library(svglite)
library(systemfonts)
library(unikn)
# library(viridis)
